# Generated by Django 4.2 on 2023-04-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_product', models.TextField()),
                ('total_for_product', models.FloatField()),
                ('reg_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
