# Generated by Django 4.2 on 2023-04-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user_product_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.product'),
        ),
    ]
