# Generated by Django 4.2 on 2023-04-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_basket_user_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='reg_data',
        ),
    ]
