# Generated by Django 4.2 on 2023-04-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_rename_cart_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quantity',
            new_name='user_product_quantity',
        ),
    ]
